name: project_euler
description: Solutions for the project euler problems written in dart
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
