/*
*   The prime 41, can be written as the sum of six consecutive primes:
*   
*   41 = 2 + 3 + 5 + 7 + 11 + 13
*   This is the longest sum of consecutive primes that adds to a prime below one-hundred.
*   
*   The longest sum of consecutive primes below one-thousand that adds to a 
*   prime, contains 21 terms, and is equal to 953.
*   
*   Which prime, below one-million, can be written as the sum of the most 
*   consecutive primes?
*/

import '../helpers/int_extensions.dart';
import '../helpers/measure_runtime.dart';

void main() {
  executeAndMeasure(solution);
}

/// Brute force (Takes ages to run, but does the job)
void solution() {
  const limit = 1000000;
  final primes = [2];
  var lower = 0;
  var upper = 0;

  for (var n = 3; n < limit; n += 2) {
    if (n.isPrime) {
      primes.add(n);
      var i = 0;
      var j = 1;
      while (i < j) {
        final sum = primes.sublist(i, j + 1).reduce((a, b) => a + b);

        if (sum < n) {
          j++;
        } else if (sum > n) {
          i++;
        } else {
          if (j - i > upper - lower) {
            lower = i;
            upper = j;
          }
          break;
        }
      }
    }
  }

  final primesRange = primes.sublist(lower, upper + 1);
  final largestPrime = primesRange.reduce((a, b) => a + b);

  print('Largest sum is $largestPrime generated by $primesRange');
}
